# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13r-3nRpE_pC2mTMIpPg3FKAPi5PztR2y
"""

import pandas as pd
import matplotlib.pyplot as plt

# URL del archivo CSV
url = "https://raw.githubusercontent.com/anujahlawat/salary-hike/main/Salary_Data.csv"

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv(url)

# Imprimir el tamaño del DataFrame (filas, columnas)
print("Tamaño del DataFrame:", df.shape)

max_experience = df["YearsExperience"].max()
print("Máximo valor de YearsOfExperience:", max_experience)

df_sorted = df.sort_values(by="Salary", ascending=True)
print(df_sorted.head())  # Mostramos las primeras filas ordenadas

df["AvgSalary"] = df["Salary"] / df["YearsExperience"]
print(df.head())  # Mostramos las primeras filas con la nueva columna

plt.scatter(df["YearsExperience"], df["Salary"], color="blue", alpha=0.5)
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Evolución del Salario según Años de Experiencia")
plt.grid(True)
plt.show()

